New schema
RHIT-XPrize/rhit-xprize-blocksworld pull request #64
Opened 2018-04-18 05:15 UTC by kgroble

This time with base implementation of actually writing things to the DB. Mostly to generate discussion, there are some things that still need to be worked out:

- Only change to the schema from last PR is moving IDs from `int` to `uuid`
- Just as Lewis finished testing the moves tracker, I redid how it works - I think its only purpose for existence is to facilitate logging, so keeping the new implementation would make sense. I'll update tests when it's not 1 in the morning
- There are inconsistencies with where pixels are used and where percentages are used. We should discuss which we want to stick with.
- There's something funny going on with the timestamps, sometimes they seem to go backwards. Thinking about just entirely refactoring how time is tracked.
- There was no attempt to fill in the training data tables in this PR, or deal intelligently with move undos. I think the main options for this are either tracking it on the server or allowing the move tracker to rewind.

2018-04-25 02:07 UTC, jcolemang commented on 2D Simulation/startAndEndGame.js
> +                        }
This is an interesting indentation choice

2018-04-25 02:08 UTC, jcolemang commented on server/create-baseline.sql
> +  text varchar(100)
It might be a good idea to make this longer

2018-04-25 02:08 UTC, jcolemang approved these changes

2018-04-25 06:15 UTC, rbubulka approved these changes

2018-04-25 12:16 UTC, Lewis-Kelley requested changes
Also be aware that you need to pull in master to fix some merge conflicts that are coming from the newly tested `movesTracker`.

2018-04-25 12:16 UTC, Lewis-Kelley commented on 2D Simulation/game.js
> +                          instructionstarttime,
Remember that we really shouldn't be tracking `instructionstarttime`. It used to be used to time how long it took the user to type their instruction from the time they first clicked in the box to the time they hit submit.

2018-04-25 12:16 UTC, Lewis-Kelley commented on 2D Simulation/movesTracker.js
> +    this.add_gesture = function (start_time, left_pos_percent, top_pos_percent) {
Ditto about the `instructionstarttime`.

2018-04-25 12:16 UTC, Lewis-Kelley commented on requirements.txt
> +uuid
Should probably go ahead and lock in a version for these two dependencies (similar to #71).

2018-04-25 12:16 UTC, Lewis-Kelley commented on server/create-baseline.sql
> +  needed_correction boolean
Come to think of it, how would we be able to find the correcting move? Would we just have to look at the next move chronologically? It might be easier to have a foreign key to an action (probably making `action_data` a supertable all of these can extend) that can be null if there was no correction and the foreign key otherwise.

2018-04-25 12:16 UTC, Lewis-Kelley commented on server/database.py
> +    cursor.execute("INSERT INTO survey(q1) values(%s)", (survey_data['q1'],))
Can we change `values` to `VALUES` to be more consistent?

2018-04-25 12:16 UTC, Lewis-Kelley commented on server/database.py
>  def store_game(db_connection, game_data):
This function's a little big overall. We could probably split it into storing the blocks and storing the actions as two separate functions.

2018-04-25 12:16 UTC, Lewis-Kelley commented on server/database.py
> +        action_type = action['type']
Similarly, if we want to go a little wild, we could split each action type into its own function.

2018-04-25 12:16 UTC, Lewis-Kelley commented on server/create-baseline.sql
>    q1 varchar(10000),
In `store_survey`, we only insert into `q1`. I don't think that we even need `q2` or `q3`, so should we just remove them from the table here?

2018-04-25 12:16 UTC, Lewis-Kelley commented on 2D Simulation/startAndEndGame.js
> +        console.log(initialInfo);
Should we remove the log?

2018-04-27 16:33 UTC, Lewis-Kelley commented
Additionally, we should update the `game` table to hold at least some of the metrics currently referenced in the Pandas analysis program.

2018-05-08 12:51 UTC, Lewis-Kelley approved these changes

2018-05-17 16:00 UTC, merged